### ISSUE TITLE
El Capitan (Mac OS X 10.11)

### ISSUE THREAD

**Issue by ericvanboven** [josephholsten/pbis#3]
Current version of PBIS does not work on this Operating System. Is this planned?

**Comment by docsmooth** [comment]
FYI, This is just a kind clone of the official PBIS git repository, and I don't think any of the developers watch the issues here. 
I did email openproject@beyondtrust.com and they said both 10.11 and 10.12 were on the roadmap for this year.

**Comment by ericvanboven** [comment]
Thank you
